-- This script creates your PostgreSQL database schema for user authentication,
-- admin roles, and the new ID generation rules.
-- Run this in your PostgreSQL tool (like pgAdmin) as your database user.

-- 1. Create a sequence for generating user IDs (e.g., POLICY_USER_00001)
CREATE SEQUENCE user_id_seq
  START WITH 1
  INCREMENT BY 1;

-- 2. Create a sequence for generating policy numbers (e.g., POLICY_NO_00001)
CREATE SEQUENCE policy_no_seq
  START WITH 1
  INCREMENT BY 1;

-- 3. Create the new USERS table for registration and login
CREATE TABLE USERS (
    user_id        VARCHAR(50) PRIMARY KEY, -- e.g., 'POLICY_USER_00001'
    email          VARCHAR(255) NOT NULL UNIQUE,
    password_hash  VARCHAR(255) NOT NULL, -- To store hashed password
    role           VARCHAR(20) DEFAULT 'MEMBER' NOT NULL, -- 'MEMBER' or 'ADMIN'
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_role CHECK (role IN ('MEMBER', 'ADMIN'))
);

-- 4. Create the POLICIES table
CREATE TABLE POLICIES (
    policy_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            VARCHAR(50) NOT NULL,
    product_name       VARCHAR(255),
    insurer_name       VARCHAR(255),
    premium            DECIMAL(10, 2),
    base_premium       DECIMAL(10, 2),
    taxes              DECIMAL(10, 2),
    policy_number      VARCHAR(100) UNIQUE,
    status             VARCHAR(50) DEFAULT 'Draft', -- 'Draft', 'Pended', 'Active', 'Lapsed'
    policy_start_date  TIMESTAMP,
    last_updated       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_policy_user
    FOREIGN KEY (user_id) REFERENCES USERS(user_id)
);

-- 5. Create the POLICY_MEMBERS table
CREATE TABLE POLICY_MEMBERS (
    member_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id      INTEGER NOT NULL,
    client_side_id VARCHAR(100) NOT NULL, -- The ID from the HTML (e.g., 'proposer' or 'dep-123')
    name           VARCHAR(255) NOT NULL,
    dob            DATE NOT NULL,
    age            INTEGER NOT NULL,
    relationship   VARCHAR(50) NOT NULL,
    kyc_status     VARCHAR(50) DEFAULT 'Outstanding', -- 'Outstanding', 'Confirmed', 'Exempt'
    
    CONSTRAINT fk_policy FOREIGN KEY (policy_id) REFERENCES POLICIES(policy_id) ON DELETE CASCADE
);

-- 6. Create the CLAIMS table
CREATE TABLE CLAIMS (
    claim_db_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id       VARCHAR(100) NOT NULL UNIQUE,
    policy_id      INTEGER NOT NULL,
    member_name    VARCHAR(255) NOT NULL,
    details        TEXT, -- Replaced Oracle CLOB with PostgreSQL TEXT
    status         VARCHAR(50) DEFAULT 'Submitted', -- 'Submitted', 'Approved', 'Rejected', 'Paid'
    submitted_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_claims_policy FOREIGN KEY (policy_id) REFERENCES POLICIES(policy_id)
);

-- 7. Create the sample Admin user
-- The password is 'admin123'
-- This is the VERIFIED, WORKING HASH
INSERT INTO USERS (user_id, email, password_hash, role)
VALUES (
    'POLICY_USER_' || LPAD(nextval('user_id_seq')::text, 5, '0'),
    'admin@securelife.com',
    '$2b$10$8KV/v7lpGER0L.n11i8IKO6h4f3AYs8GGZVh1ynoUdGB9slJpKyPO', -- 'admin123'
  --  '$2a$10$KxR..A0k6jJqr02/y1TjTuVbMWwV.zJ3.H8V1.kY/e8/D9m/E2.eO', -- 'admin123'
    'ADMIN'
);

-- 8. Add a unique index on client_side_id and policy_id
-- This prevents duplicate members (e.g. two 'proposer' entries) for the *same* policy.
CREATE UNIQUE INDEX idx_policy_client_id ON POLICY_MEMBERS (policy_id, client_side_id);